os:
  linux

dist:
  xenial

services:
  - postgresql
  - mysql

language:
  python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - cp .env.example .env
  - psql -c 'CREATE DATABASE test;' -U postgres
  - mysql -e 'CREATE DATABASE test CHARACTER SET utf8 COLLATE utf8_general_ci;'
  - openssl aes-256-cbc -K $encrypted_4885f94bfb6d_key -iv $encrypted_4885f94bfb6d_iv -in .google.json.enc -out .google.json -d

install:
  # TODO: remove after
  # https://stackoverflow.com/questions/63902467/module-six-moves-has-no-attribute-collections-abc
  - pip install 'six>=1.13'
  - make install

script:
  - make test-ci

after_success:
  - coveralls

jobs:
  include:
    - stage: release
      if: tag IS present
      python: 3.8
      deploy:
        edge: true
        provider: pypi
        user: roll
        distributions: sdist bdist_wheel
        on:
          tags: true
        password:
          secure: HcQzBXtTGiZW6WlqMhUX4KIM8slf+fCqc0jiE0Fak/8Po4seZqoHqL6at1ELwL5vjH9lkSU4fmEWcNNzTvtWJncTUE5/T+UzOTgmsrqvLPK4ACVkv7obCQHSrUZKnzaSyfnmq89M77Gd2gahfs0tyDQyeoLROX260Pu1MugtXzQ=
