name: project

on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - reopened

jobs:
  project-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign to project
        uses: leonsteinhaeuser/project-beta-automations@v1.2.1
        with:
          gh_token: ${{ secrets.PROJECT_TOKEN }}
          resource_node_id: ${{ github.event_name == 'issues' && github.event.issue.node_id || github.event.pull_request.node_id }}
          organization: frictionlessdata
          project_id: 16
          status_value: Inbox
